import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageJsonPath = resolve(root, "package.json");
const manifestPath = resolve(root, "extension", "manifest.json");
const versionSourcePath = resolve(root, "src", "version.ts");
const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));
const version = packageJson.version;

if (typeof version !== "string" || !/^\d+(?:\.\d+){0,3}$/u.test(version)) {
  throw new Error(`Package version is not a Chrome-compatible numeric version: ${String(version)}`);
}

const generatedSource = `// Generated by scripts/sync-version.mjs from package.json. Do not edit by hand.\nexport const ASR_VERSION = ${JSON.stringify(version)};\n`;
const currentSource = await readFile(versionSourcePath, "utf8");
if (currentSource !== generatedSource) await writeFile(versionSourcePath, generatedSource, "utf8");

const currentManifest = await readFile(manifestPath, "utf8");
const versionPattern = /("version"\s*:\s*)"[^"]+"/u;
if (!versionPattern.test(currentManifest)) throw new Error("Extension manifest has no version field");
const generatedManifest = currentManifest.replace(versionPattern, `$1${JSON.stringify(version)}`);
if (currentManifest !== generatedManifest) await writeFile(manifestPath, generatedManifest, "utf8");

console.log(`Synchronized runtime and extension version to ${version}`);
